name: Changesets
on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    uses: driimus/shared-workflows/.github/workflows/publish.yml@feat/publish
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
